#!/usr/bin/env python3
"""
Environment Setup Script for Adobe V4
This script helps you configure your environment variables and validates the setup.
"""

import os
import sys
import secrets
from pathlib import Path

def generate_secret_key():
    """Generate a secure secret key."""
    return secrets.token_hex(32)

def create_env_file():
    """Create or update the .env file with proper configuration."""
    env_path = Path('.env')
    
    # Check if .env file exists
    if env_path.exists():
        print("📁 .env file already exists")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("❌ Setup cancelled")
            return False
    
    # Get user input for configuration
    print("\n🔧 Setting up Adobe V4 Environment Configuration")
    print("="*50)
    
    # Google API Key
    print("\n🔑 Google API Configuration:")
    print("Get your Google API key from: https://console.cloud.google.com/")
    google_api_key = input("Enter your Google API Key: ").strip()
    
    # Azure Speech Key
    print("\n🔊 Azure Speech Services Configuration:")
    print("Get your Azure Speech key from: https://portal.azure.com/")
    azure_speech_key = input("Enter your Azure Speech Key: ").strip()
    azure_region = input("Enter Azure Region (default: centralindia): ").strip() or "centralindia"
    
    # AWS Configuration (optional)
    print("\n☁️ AWS Configuration (optional - press Enter to skip):")
    aws_access_key = input("Enter AWS Access Key ID: ").strip()
    aws_secret_key = input("Enter AWS Secret Access Key: ").strip()
    aws_region = input("Enter AWS Region (default: us-east-1): ").strip() or "us-east-1"
    
    # TTS Provider
    print("\n🎤 TTS Provider Configuration:")
    tts_provider = input("Choose TTS Provider (azure/aws, default: azure): ").strip().lower() or "azure"
    
    # Server Configuration
    print("\n🌐 Server Configuration:")
    host = input("Enter host (default: 0.0.0.0): ").strip() or "0.0.0.0"
    port = input("Enter port (default: 8000): ").strip() or "8000"
    
    # Generate secret key
    secret_key = generate_secret_key()
    
    # Create .env content
    env_content = f"""# =============================================================================
# ADOBE V4 - ENVIRONMENT CONFIGURATION
# =============================================================================
# Generated by setup_env.py - DO NOT EDIT MANUALLY

# =============================================================================
# GOOGLE API CONFIGURATION
# =============================================================================
GOOGLE_API_KEY={google_api_key}

# =============================================================================
# AZURE SPEECH SERVICES CONFIGURATION
# =============================================================================
AZURE_SPEECH_KEY={azure_speech_key}
AZURE_SPEECH_REGION={azure_region}

# =============================================================================
# AWS CONFIGURATION
# =============================================================================
AWS_ACCESS_KEY_ID={aws_access_key}
AWS_SECRET_ACCESS_KEY={aws_secret_key}
AWS_REGION={aws_region}

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
TTS_PROVIDER={tts_provider}
HOST={host}
PORT={port}
DEBUG=False

# File Upload Configuration
MAX_FILE_SIZE=10485760
ALLOWED_EXTENSIONS=pdf,docx,txt

# Document Processing Configuration
MAX_CHUNK_SIZE=200
CHUNK_OVERLAP=50
MIN_CHUNK_LENGTH=50

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
SECRET_KEY={secret_key}
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOG_LEVEL=INFO
LOG_FILE=adobev4.log

# =============================================================================
# STORAGE CONFIGURATION
# =============================================================================
DOCUMENTS_DIR=documents
AUDIO_DIR=audio
INDEX_DIR=index
UPLOADS_DIR=uploads

# =============================================================================
# AI MODEL CONFIGURATION
# =============================================================================
EMBEDDING_MODEL=all-MiniLM-L6-v2
GEMINI_MODEL=gemini-1.5-flash

# =============================================================================
# PERFORMANCE CONFIGURATION
# =============================================================================
WORKERS=4
EMBEDDINGS_CACHE_SIZE=1000
MAX_CONCURRENT_REQUESTS=10

# =============================================================================
# DEVELOPMENT CONFIGURATION
# =============================================================================
DEVELOPMENT_MODE=True
VERBOSE_LOGGING=False
"""
    
    # Write .env file
    try:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(env_content)
        print(f"\n✅ .env file created successfully at {env_path.absolute()}")
        return True
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def validate_env_file():
    """Validate the .env file and check required variables."""
    try:
        from config import validate_and_print_config
        return validate_and_print_config()
    except ImportError:
        print("❌ Could not import config module. Make sure you're in the correct directory.")
        return False
    except Exception as e:
        print(f"❌ Error validating configuration: {e}")
        return False

def install_dependencies():
    """Install required Python packages."""
    print("\n📦 Installing required dependencies...")
    
    # Check if python-dotenv is installed
    try:
        import dotenv
        print("✅ python-dotenv is already installed")
    except ImportError:
        print("📥 Installing python-dotenv...")
        os.system("pip install python-dotenv")
    
    # Check other dependencies
    required_packages = [
        'fastapi',
        'uvicorn',
        'google-generativeai',
        'azure-cognitiveservices-speech',
        'boto3',
        'sentence-transformers',
        'faiss-cpu',
        'PyPDF2',
        'python-docx',
        'pydub'
    ]
    
    for package in required_packages:
        try:
            __import__(package.replace('-', '_'))
            print(f"✅ {package} is already installed")
        except ImportError:
            print(f"📥 Installing {package}...")
            os.system(f"pip install {package}")

def main():
    """Main setup function."""
    print("🚀 Adobe V4 Environment Setup")
    print("="*40)
    
    # Check if we're in the right directory
    if not Path('main.py').exists():
        print("❌ Error: main.py not found. Please run this script from the adobev4 directory.")
        sys.exit(1)
    
    # Install dependencies
    install_dependencies()
    
    # Create .env file
    if create_env_file():
        print("\n🔍 Validating configuration...")
        if validate_env_file():
            print("\n🎉 Setup completed successfully!")
            print("\n📝 Next steps:")
            print("1. Start the server: python main.py")
            print("2. Or run with uvicorn: uvicorn main:app --reload")
            print("3. Access the API at: http://localhost:8000")
            print("4. View API docs at: http://localhost:8000/docs")
        else:
            print("\n⚠️ Setup completed but configuration validation failed.")
            print("Please check your .env file and ensure all required variables are set.")
    else:
        print("\n❌ Setup failed. Please try again.")

if __name__ == "__main__":
    main()
